### ISSUE TITLE
"Class App\Http\Controllers\OTPSender does not exist"

### ISSUE THREAD

**Issue by prokawsar** [aqlx86/sms-otp#1]
I followed your given instruction and this error occurred.

Laravel version 5.5

**Comment by aqlx86** [comment]
hi @prokawsar 

did you have "use SMSOTP\OTPSender"

**Comment by prokawsar** [comment]
@aqlx86  Thanks for the reply
I added the class. now it's saying "invalid isms credentials"
How to configure ISMS?

**Comment by aqlx86** [comment]
@prokawsar you need to have an account on isms.

But if you have other sms provider you can extend the functionality, please see Extendin section of the readme.

**Comment by drashtiSeo** [comment]
use SMSOTP\OTPSender - this works @aqlx86  thanks

**Comment by aqlx86** [comment]
closing
