### ISSUE TITLE
Should include agreedterm in Message.php

### ISSUE THREAD

**Issue by wanamra** [aqlx86/sms-otp#2]
public function to_array()
{
        return [
            $this->recipient->type() => $this->recipient(),
            'msg' => $this->message(),
            'type' => $this->type(),
            'agreedterm' => 'YES',
            'senderid' => $this->sender_id
        ];
 }

//Agreed iSMS Term and Condition below:
//https://www.isms.com.my/user-agreement.php
//,API will filter your sms if you do not agreed with the agreement.

**Comment by aqlx86** [comment]
this is new.. could you create a request?

thanks
